# Generated by Django 4.2 on 2023-05-01 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='canban.board', verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='column',
            name='title_en',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='column',
            name='title_ru',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='column',
            name='title_uz',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='canban.column', verbose_name='Column'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
    ]
