# Generated by Django 4.2 on 2023-05-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canban', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Board title'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title_en',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Board title'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Board title'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Board title'),
        ),
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Column title'),
        ),
        migrations.AlterField(
            model_name='column',
            name='title_en',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Column title'),
        ),
        migrations.AlterField(
            model_name='column',
            name='title_ru',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Column title'),
        ),
        migrations.AlterField(
            model_name='column',
            name='title_uz',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Column title'),
        ),
    ]
